// frontend/app/blog/[slug]/page.tsx
import { PortableText } from '@portabletext/react'
import { client } from '@/lib/sanity'
import { resolver } from '@/lib/routes'

interface Props {
  params: Promise<{ slug: string }>
}

export default async function BlogPostPage({ params }: Props) {
  const { slug } = await params

  const post = await client.fetch(
    `*[_type == "blogPost" && slug.current == $slug][0]{
      _id, title, body
    }`,
    { slug }
  )

  if (!post) {
    return <h1>Blog post not found</h1>
  }

  // Pre-load all route map shards for synchronous PT link resolution
  const urlMap = await resolver.preload()

  return (
    <article>
      <nav><a href="/">← Home</a></nav>
      <h1>{post.title}</h1>
      {post.body && (
        <PortableText
          value={post.body}
          components={{
            marks: {
              internalLink: ({ value, children }: any) => {
                const url = urlMap.get(value.reference._ref)
                return url ? <a href={url}>{children}</a> : <span>{children}</span>
              },
            },
          }}
        />
      )}
    </article>
  )
}

// examples/nuxt/app/pages/blog/[slug].vue
<script setup lang="ts">
import { BLOG_POST_BY_SLUG_QUERY } from '~/lib/queries'

const route = useRoute()

const { data } = await useAsyncData(`blog-${route.params.slug}`, async () => {
  const client = useSanityClient()
  const resolver = useRouteResolver()

  const [post, urlMap] = await Promise.all([
    client.fetch(BLOG_POST_BY_SLUG_QUERY, { slug: route.params.slug as string }),
    resolver.preload(),
  ])

  return { post, urlMap }
})

if (!data.value?.post) {
  throw createError({ statusCode: 404, statusMessage: 'Blog post not found' })
}
</script>

<template>
  <article v-if="data?.post">
    <h1>{{ data.post.title }}</h1>
    <PortableTextBody :value="data.post.body" :url-map="data.urlMap" />
  </article>
</template>
