// examples/nuxt/app/components/PortableTextBody.vue
<script setup lang="ts">
import { getPath } from '@sanity/routes'
import { PortableText } from '@portabletext/vue'
import { h } from 'vue'

const props = defineProps<{
  value: any
  urlMap: Record<string, string>
}>()

const components = {
  marks: {
    internalLink: ({ value: mark }: any, { slots }: any) => {
      const url = mark?.reference ? props.urlMap[mark.reference._ref] : undefined
      const href = url ? (getPath(url) ?? url) : '#'
      return url
        ? h('a', { href }, slots.default?.())
        : h('span', {}, slots.default?.())
    },
  },
}
</script>

<template>
  <PortableText :value="value" :components="components" />
</template>

// examples/spa/src/components/PortableTextBody.tsx
import { PortableText, type PortableTextComponents, type PortableTextProps } from '@portabletext/react'
import { Link } from 'react-router'
import { getPath } from '@sanity/routes'

interface Props {
  value: PortableTextProps['value']
  urlMap: Record<string, string>
}

const createComponents = (urlMap: Record<string, string>): PortableTextComponents => ({
  marks: {
    internalLink: ({ children, value: mark }) => {
      const docId = mark?.reference?._ref
      const url = docId ? urlMap[docId] : undefined
      const href = url ? getPath(url) ?? url : undefined

      if (!href) return <span>{children}</span>

      return <Link to={href}>{children}</Link>
    },
  },
})

export default function PortableTextBody({ value, urlMap }: Props) {
  return <PortableText value={value} components={createComponents(urlMap)} />
}
