// examples/nuxt/app/components/PortableTextBody.vue
<script setup lang="ts">
import { getPath } from '@sanity/routes'
import { PortableText } from '@portabletext/vue'
import { h } from 'vue'

const props = defineProps<{
  value: any
  urlMap: Record<string, string>
}>()

const components = {
  marks: {
    internalLink: ({ value: mark }: any, { slots }: any) => {
      const url = mark?.reference ? props.urlMap[mark.reference._ref] : undefined
      const href = url ? (getPath(url) ?? url) : '#'
      return url
        ? h('a', { href }, slots.default?.())
        : h('span', {}, slots.default?.())
    },
  },
}
</script>

<template>
  <PortableText :value="value" :components="components" />
</template>

// examples/tanstack-start/src/components/PortableTextBody.tsx
import { PortableText } from '@portabletext/react'
import { getPath } from '@sanity/routes'

interface Props {
  value: any
  urlMap: Record<string, string>
}

/**
 * Portable Text renderer with internal link resolution.
 *
 * Uses a pre-loaded URL map (Record) for synchronous link resolution.
 * TanStack Start uses a custom serializer that doesn't support Map,
 * so Record<string, string> is the correct type here.
 */
export function PortableTextBody({ value, urlMap }: Props) {
  if (!value) return null

  return (
    <PortableText
      value={value}
      components={{
        marks: {
          internalLink: ({ value: mark, children }) => {
            const url = mark?.reference
              ? urlMap[mark.reference._ref]
              : undefined
            const href = url ? (getPath(url) ?? url) : '#'
            return url ? <a href={href}>{children}</a> : <span>{children}</span>
          },
        },
      }}
    />
  )
}
