// examples/nuxt/app/pages/blog/[slug].vue
<script setup lang="ts">
import { BLOG_POST_BY_SLUG_QUERY } from '~/lib/queries'

const route = useRoute()

const { data } = await useAsyncData(`blog-${route.params.slug}`, async () => {
  const client = useSanityClient()
  const resolver = useRouteResolver()

  const [post, urlMap] = await Promise.all([
    client.fetch(BLOG_POST_BY_SLUG_QUERY, { slug: route.params.slug as string }),
    resolver.preload(),
  ])

  return { post, urlMap }
})

if (!data.value?.post) {
  throw createError({ statusCode: 404, statusMessage: 'Blog post not found' })
}
</script>

<template>
  <article v-if="data?.post">
    <h1>{{ data.post.title }}</h1>
    <PortableTextBody :value="data.post.body" :url-map="data.urlMap" />
  </article>
</template>

// examples/nextjs/app/blog/[slug]/page.tsx
import { sanityFetch } from '@/lib/live'
import { resolver } from '@/lib/routes'
import { PortableTextBody } from '@/components/PortableTextBody'
import { BLOG_POST_BY_SLUG_QUERY } from '@/lib/queries'

interface Props {
  params: Promise<{ slug: string }>
}

export default async function BlogPostPage({ params }: Props) {
  const { slug } = await params

  const { data: post } = await sanityFetch({
    query: BLOG_POST_BY_SLUG_QUERY,
    params: { slug },
  })

  if (!post) {
    return <h1>Blog post not found</h1>
  }

  const urlMap = await resolver.preload()

  return (
    <article>
      <nav><a href="/">← Home</a></nav>
      <h1>{post.title}</h1>
      <PortableTextBody value={post.body} urlMap={urlMap} />
    </article>
  )
}
